"""
Usage:  [OPTIONS] COMMAND [ARGS]...

  A cli for {{ cookiecutter.package_name }}.

Options:
  --help  Show this message and exit.
"""
from pathlib import Path
import re
import os

from {{ cookiecutter.package_name }}.{{ cookiecutter.project_slug }} import app

import click


@click.group()
def main():
    """A cli for {{ cookiecutter.package_name }}."""
    pass


@main.command()
@click.option('--host', default='127.0.0.1')
@click.option('--port', default=8000)
def runserver(host, port):
    app.run(host=host, port=port)


def transform_module_text(matchobj):
    """Return the text from the module with the docstring generated by click prepended to it."""
    with click.Context(main) as ctx:
        docstring = os.linesep.join(['"""', ctx.get_help(), '"""'])

    return docstring + os.linesep + ''.join(matchobj.groups()[1:])


# replace this module's docstring with the one generated from top-level cli entrypoint
transformed_module_text = re.sub(
    re.compile(r'(.*?)(from|import)(.*)', re.DOTALL | re.MULTILINE),
    transform_module_text,
    Path(__file__).read_text()
)
with Path(__file__).open('w') as this_module:
    this_module.write(transformed_module_text)

if __name__ == "__main__":
    main()
